/* placeholder: generated by sokol-shdc from shaders/glyph_coverage.glsl */

#ifndef GLYPH_COVERAGE_SOKOL_H
#define GLYPH_COVERAGE_SOKOL_H

#include <sokol/sokol_gfx.h>

#if defined(__cplusplus)
extern "C" {
#endif

sg_shader glyph_coverage_shader_desc(sg_backend backend);

#if defined(__cplusplus)
}
#endif

#endif // GLYPH_COVERAGE_SOKOL_H
