#!/bin/sh
# bin2c.sh INPUT SYMBOL
#
# Emit (to stdout) a C header embedding the bytes of INPUT as
#   static const unsigned char SYMBOL[] = { ... };
#   static const unsigned int  SYMBOL_len = sizeof(SYMBOL);
#
# Uses od(1) only (POSIX), so no xxd dependency. Used to embed compiled SPIR-V
# (see src/shaders/) into the build.
set -eu

in=$1
sym=$2
guard=$(printf '%s' "$sym" | tr '[:lower:]' '[:upper:]')_H

printf '/* Generated by build-aux/bin2c.sh from %s. Do not edit. */\n' "$(basename "$in")"
printf '#ifndef %s\n#define %s\n' "$guard" "$guard"
printf 'static const unsigned char %s[] = {\n' "$sym"
od -An -v -tu1 "$in" | awk '
    { for (i = 1; i <= NF; i++) { printf " %s,", $i; if (++n % 16 == 0) printf "\n" } }
    END { if (n % 16 != 0) printf "\n" }'
printf '};\n'
printf 'static const unsigned int %s_len = sizeof(%s);\n' "$sym" "$sym"
printf '#endif /* %s */\n' "$guard"
