/*
 * portty — CharmTone palette of brand colors as packed RGBA32
 *
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2026 Thomas Christensen
 */

/*
 * CharmTone palette — 70 brand colors from charm.land
 *
 * Packed as RGBA32 (0xRRGGBBAA) for direct use in rendering.
 * Generated from github.com/charmbracelet/x/exp/charmtone.
 *
 * Homage to Charmbracelet — thanks for making the terminal
 * a more colorful place.
 */

#ifndef CHARMTONES_H
#define CHARMTONES_H

#include <stdint.h>

/* Reds / Oranges */
#define CHARMTONE_CUMIN    0xBF976FFFu
#define CHARMTONE_TANG     0xFF985AFFu
#define CHARMTONE_YAM      0xFFB587FFu
#define CHARMTONE_PAPRIKA  0xD36C64FFu
#define CHARMTONE_BENGAL   0xFF6E63FFu
#define CHARMTONE_UNI      0xFF937DFFu
#define CHARMTONE_SRIRACHA 0xEB4268FFu

/* Pinks / Reds */
#define CHARMTONE_CORAL   0xFF577DFFu
#define CHARMTONE_SALMON  0xFF7F90FFu
#define CHARMTONE_CHILI   0xE23080FFu
#define CHARMTONE_CHERRY  0xFF388BFFu
#define CHARMTONE_TUNA    0xFF6DAAFFu
#define CHARMTONE_MACARON 0xE940B0FFu
#define CHARMTONE_PONY    0xFF4FBFFFu
#define CHARMTONE_CHEEKY  0xFF79D0FFu

/* Magentas / Purples */
#define CHARMTONE_FLAMINGO 0xF947E3FFu
#define CHARMTONE_DOLLY    0xFF60FFFFu
#define CHARMTONE_BLUSH    0xFF84FFFFu
#define CHARMTONE_URCHIN   0xC337E0FFu
#define CHARMTONE_MOCHI    0xEB5DFFFFu
#define CHARMTONE_LILAC    0xF379FFFFu
#define CHARMTONE_PRINCE   0x9C35E1FFu
#define CHARMTONE_VIOLET   0xC259FFFFu
#define CHARMTONE_MAUVE    0xD46EFFFFu

/* Violets / Blues */
#define CHARMTONE_GRAPE    0x7134DDFFu
#define CHARMTONE_PLUM     0x9953FFFFu
#define CHARMTONE_ORCHID   0xAD6EFFFFu
#define CHARMTONE_JELLY    0x4A30D9FFu
#define CHARMTONE_CHARPLE  0x6B50FFFFu
#define CHARMTONE_HAZY     0x8B75FFFFu
#define CHARMTONE_OX       0x3331B2FFu
#define CHARMTONE_SAPPHIRE 0x4949FFFFu
#define CHARMTONE_GUPPY    0x7272FFFFu

/* Blues / Cyans */
#define CHARMTONE_OCEANIA 0x2B55B3FFu
#define CHARMTONE_THUNDER 0x4776FFFFu
#define CHARMTONE_ANCHOVY 0x719AFCFFu
#define CHARMTONE_DAMSON  0x007AB8FFu
#define CHARMTONE_MALIBU  0x00A4FFFFu
#define CHARMTONE_SARDINE 0x4BFEFEFFu
#define CHARMTONE_ZINC    0x10B1AEFFu
#define CHARMTONE_TURTLE  0x0ADCD9FFu
#define CHARMTONE_LICHEN  0x5CDFEAFFu

/* Greens */
#define CHARMTONE_GUAC  0x12C78FFFu
#define CHARMTONE_JULEP 0x00FFB2FFu
#define CHARMTONE_BOK   0x68FFD6FFu

/* Yellows */
#define CHARMTONE_MUSTARD 0xF5EF34FFu
#define CHARMTONE_CITRON  0xE8FF27FFu
#define CHARMTONE_ZEST    0xE8FE96FFu
#define CHARMTONE_BUTTER  0xFFFAF1FFu

/* Neutrals (dark to light) */
#define CHARMTONE_PEPPER 0x201F26FFu
#define CHARMTONE_BBQ    0x2D2C36FFu
#define CHARMTONE_CHAR   0x3A3943FFu
#define CHARMTONE_IRON   0x4D4C57FFu
#define CHARMTONE_OYSTER 0x605F6BFFu
#define CHARMTONE_SQUID  0x858392FFu
#define CHARMTONE_STEAM  0xA2A0ADFFu
#define CHARMTONE_SMOKE  0xBFBCC8FFu
#define CHARMTONE_STEEP  0xD6D3DCFFu
#define CHARMTONE_SASH   0xECEBF0FFu
#define CHARMTONE_SALT   0xF7F6FBFFu
#define CHARMTONE_SODA   0xFBFBFBFFu

/* Extras */
#define CHARMTONE_DARPLE  0x5B40ECFFu
#define CHARMTONE_LARPLE  0x7B62FFFFu
#define CHARMTONE_PICKLE  0x00A475FFu
#define CHARMTONE_GATOR   0x18463DFFu
#define CHARMTONE_SPINACH 0x1C3634FFu
#define CHARMTONE_POM     0xAB2454FFu
#define CHARMTONE_STEAK   0x582238FFu
#define CHARMTONE_TOAST   0x412130FFu
#define CHARMTONE_ICE     0x00FFFCFFu

/* ------------------------------------------------------------------ */
/* ANSI 0-15 aliases (match coffer's palette.c)                       */
/* ------------------------------------------------------------------ */

#define CHARMTONE_ANSI_BLACK   CHARMTONE_PEPPER
#define CHARMTONE_ANSI_RED     CHARMTONE_CORAL
#define CHARMTONE_ANSI_GREEN   CHARMTONE_GUAC
#define CHARMTONE_ANSI_YELLOW  CHARMTONE_MUSTARD
#define CHARMTONE_ANSI_BLUE    CHARMTONE_CHARPLE
#define CHARMTONE_ANSI_MAGENTA CHARMTONE_DOLLY
#define CHARMTONE_ANSI_CYAN    CHARMTONE_TURTLE
#define CHARMTONE_ANSI_WHITE   CHARMTONE_SMOKE

#define CHARMTONE_ANSI_BRIGHT_BLACK   CHARMTONE_OYSTER
#define CHARMTONE_ANSI_BRIGHT_RED     CHARMTONE_SALMON
#define CHARMTONE_ANSI_BRIGHT_GREEN   CHARMTONE_JULEP
#define CHARMTONE_ANSI_BRIGHT_YELLOW  CHARMTONE_ZEST
#define CHARMTONE_ANSI_BRIGHT_BLUE    CHARMTONE_HAZY
#define CHARMTONE_ANSI_BRIGHT_MAGENTA CHARMTONE_BLUSH
#define CHARMTONE_ANSI_BRIGHT_CYAN    CHARMTONE_BOK
#define CHARMTONE_ANSI_BRIGHT_WHITE   0xFFFDF5FFu /* cream, not Butter */

/* Unpack macros for components */
#define CHARMTONE_R(c) (uint8_t)(((c) >> 24) & 0xFF)
#define CHARMTONE_G(c) (uint8_t)(((c) >> 16) & 0xFF)
#define CHARMTONE_B(c) (uint8_t)(((c) >> 8) & 0xFF)
#define CHARMTONE_A(c) (uint8_t)((c) & 0xFF)

#endif /* CHARMTONES_H */